PROJECT_NAME = 'Plantagotchi'
SSID = 'Alvaro-AP'
PSSW = 'hola1234'
OLED_WIDTH = 128
OLED_HEIGHT = 64
FIRESTORE_API_KEY = 'AIzaSyAUIuBk5mJt8VqfK4jMvJkizbj0luVPbxI'
FIRESTORE_PROJECT_ID = 'workshop-fa2ff'
SEND_REQUEST_SECS = 60
MAX_RECONNECTS = 5
TIMEZONE = "America/Costa_Rica"
ENABLE_LOGS = True
BYTE = 8

MONITOR_WORKFLOW = 'MONITOR_WORKFLOW'
CALIBRATION_MENU_WORKFLOW = 'CALIBRATION_MENU_WORKFLOW'
SET_SENSOR_MAX_CALIBRATION_VALUE = 'SET_SENSOR_MAX_CALIBRATION_VALUE'
SET_SENSOR_MIN_CALIBRATION_VALUE = 'SET_SENSOR_MIN_CALIBRATION_VALUE'
